apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Values.externalDatabase.host }}"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.externalDatabase.user }}"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secret
                  key: password
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.externalDatabase.database }}"
          ports:
            - containerPort: 80
